### ISSUE TITLE
NullPointerException thrown when using query bean generated

### ISSUE THREAD

**Issue by richdyang** [ebean-orm/ebean-querybean#34]
Hi, @rbygrave 

This is the source code generated by query bean enhancer for intellij (this plugin is: Ebean 8.x Enhancement).
```
/**
 * Query bean for User.
 * 
 * THIS IS A GENERATED OBJECT, DO NOT MODIFY THIS CLASS.
 */
@TypeQueryBean
public class QUser extends TQRootBean<User,QUser> {

  private static final QUser _alias = new QUser(true);

  /**
   * Return the shared 'Alias' instance used to provide properties to 
   * <code>select()</code> and <code>fetch()</code> 
   */
  public static QUser alias() {
    return _alias;
  }

  public PLong<QUser> id;
  public PString<QUser> wechatOpenid;
  public PString<QUser> wechatUnionid;
  public PString<QUser> userName;
  public PString<QUser> email;
  public PString<QUser> mobile;
  public PString<QUser> encryptedPassword;
  public PString<QUser> salt;
  public PTimestamp<QUser> createdAt;
  public PTimestamp<QUser> lastLoginAt;
  public PInteger<QUser> statLogined;
  public PTimestamp<QUser> lastErrorLoginAt;
  public PInteger<QUser> statErrorLogin;
  public PString<QUser> status;
  public PString<QUser> validationStatus;


  /**
   * Construct with a given EbeanServer.
   */
  public QUser(EbeanServer server) {
    super(User.class, server);
  }

  /**
   * Construct using the default EbeanServer.
   */
  public QUser() {
    super(User.class);
  }

  /**
   * Construct for Alias.
   */
  private QUser(boolean dummy) {
    super(dummy);
  }

  /**
   * Provides static properties to use in <em> select() and fetch() </em>
   * clauses of a query. Typically referenced via static imports. 
   */
  public static class Alias {
    public static PLong<QUser> id = _alias.id;
    public static PString<QUser> wechatOpenid = _alias.wechatOpenid;
    public static PString<QUser> wechatUnionid = _alias.wechatUnionid;
    public static PString<QUser> userName = _alias.userName;
    public static PString<QUser> email = _alias.email;
    public static PString<QUser> mobile = _alias.mobile;
    public static PString<QUser> encryptedPassword = _alias.encryptedPassword;
    public static PString<QUser> salt = _alias.salt;
    public static PTimestamp<QUser> createdAt = _alias.createdAt;
    public static PTimestamp<QUser> lastLoginAt = _alias.lastLoginAt;
    public static PInteger<QUser> statLogined = _alias.statLogined;
    public static PTimestamp<QUser> lastErrorLoginAt = _alias.lastErrorLoginAt;
    public static PInteger<QUser> statErrorLogin = _alias.statErrorLogin;
    public static PString<QUser> status = _alias.status;
    public static PString<QUser> validationStatus = _alias.validationStatus;
  }
}
```

After it is compiled, I decompiled the class file, and found some extra methods were weaved, like for property userName, there would be a _userName() method:

```
    public PString<QUser> _userName() {
        if(this.userName == null) {
            this.userName = new PString("userName", this);
        }

        return this.userName;
    }
```

But in my code I use it as:
```
new QUser().userName
```

Obviously, the `userName` property was never initialized.

So until now, what did I missed?

**Comment by rbygrave** [comment]
The video https://youtu.be/Kp528zWlbqU ... goes through the enhancement details, it's pretty long but discusses why query beans work in this manor.

The calling code needs to be enhanced which converts new QUser().userName to new QUser()._userName() ... this would be what is missing in the above.  Normally I'd expect the IDE plugin (for IDEA or Eclipse) to be running in the IDE to perform this enhancement during development and the maven plugin or tile to do the enhancement at build time.

The enhancement of calling code requires META-INF / ebean-typequery.mf   or META-INF / ebean.mf to define the packages that contain query beans.

At some point I'll look to try the alternate approach with Kotlin (that unlike Java has properties) which means only the query beans themselves need enhancement which is arguably much nicer/cleaner.

**Comment by richdyang** [comment]
Thanks, Rob. The intellij plugin enhanced my query bean and entity, but I don't know why it did not enhance my calling code.

**Comment by rbygrave** [comment]
It could be either the manifest file is missing for some reason (META-INF/ebean-typequery.mf or META-INF/ebean.mf) ... or that the code containing the query bean also has entity bean enhancement (perhaps @Transactional ?) 

Can you create put an example application somewhere (like github) to show the issue?

**Comment by albertoclarit** [comment]
i have this issue...querybean properties are null unless i use the alias method

**Comment by hofmanndavid** [comment]
I have the same issue. And it's not the first time this happens. I am sure the ebean.mf file is there. It would be god if ebean can at least log when it finds or does not find that file so it's easier to debug.

**Comment by hofmanndavid** [comment]
https://ebean.io/docs/trouble-shooting

The value for querybean-packages in ebean.mf must cover all the code that "uses" query bean generated code. Unlike what the property name suggests, it is NOT the package of the query beans themselves.

**Comment by rbygrave** [comment]
So I'm guessing that the ebean.mf file was there but that the querybean-packages didn't include all the "uses" of query beans.

This is kind of tough because Java still doesn't have 'properties' yet (getter/setter/property).  So the design for querybeans picked readability of the query beans (by simulating properties) over the simplicity of using methods and only needing to enhance the query beans themselves.

If Java gets 'properties' support or people use Kotlin or people can live with this as a trouble shooting issue (For Java we need to enhance the code that uses query beans) ... then the improved readability would be the correct call as I see it.

Cheers, Rob.

**Comment by hofmanndavid** [comment]
I am a super fan of how the query beans work. I think is incredibly awesome.

But what about 'magically' finding the root package of the project. while enhance takes place. Clearly printing out what the guess was and, how to overwrite it so that by default people don't get NullPointerException without much context to get your head around how to solve it.

**Comment by rbygrave** [comment]
> 'magically' finding the root package of the project. while enhance takes place

Hmmm - not sure how it could do that ... maybe something like:
- If there is an ebean.mf with a entity-packages but no querybean-packages ... then it defaults to the top package of the entity-packages?

Might need to detect language (Java or Kotlin) as with Kotlin we only enhance the query beans themselves.

Yeah, needs more thinking here ...
