### ISSUE TITLE
ENH: Add PLocale to support java.util.Locale property types 

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean-querybean#44]

**Comment by soberich** [comment]
@rbygrave just in s meanwhile, do you think you know why is this `io.ebean:ebean-querybean` seems to be getting into neither jcenter nor maven central? I see `io.ebean:ebean` released less than a day ago is already there but this artifact is not..

**Comment by rbygrave** [comment]
No I don't know.  

It looks like 11.25.1 hasn't made it into central (and now never will).  When we release the artifacts go into the oss.sonatype.org staging area.  From there we close and release that, after that it should make it to central about 20 mins after that.

From memory I've seen 1 other release (in all the 12 odd years I've been releasing artifacts to central) that similarly never made it to central.  Given the huge job Sonatype do for us for free we'll take that.

I released 11.26.1 the other night and I see that made it to central.

Cheers, Rob.
