### ISSUE TITLE
ENH: Allow ScalarTypes to be used in querybeans

### ISSUE THREAD

**Issue by tobias-** [ebean-orm/ebean-querybean#74]
This is the feature request for https://groups.google.com/g/ebean/c/aZ4Nv1_Z6XM 

I've made some solution B PRs for it as well.

Original:
Rob Bygrave
Oct 3, 2020, 12:38:48 AM (5 days ago) 
to ebean@googlegroups
> .eq("phoneNumber.phoneNumber", incomingPhoneNumber.msisdn)

Note that with ScalarTypes (and also with javax.persistence.AttributeConverter ... which internally become ScalarTypes via ScalarTypeWrapper and AttributeConverterAdapter) we can bind these types directly in our query expressions so the above could be written as:

.eq("phoneNumber", incomingPhoneNumber)       // Ebean knows how to "unwrap" the scalar type, we don't need to  

So for query beans we would actually be targeting to do:

QMappingDBO(database)
...
.phoneNumber.eq(incomingPhoneNumber)     // where incomingPhoneNumber is of type PhoneNumber which is a ScalarType
.findOne() 

Q: So can we do this?  [... it's a bit complex to parse these in the KAPT generation?]

Well we probably have 2 options to achieve this but firstly we have to make a reasonable guess as to what expressions are valid / proper for a ScalarType that Ebean doesn't know about.  We would probably guess that it would be ok to have the same expressions as either:
- PBaseCompareable with expressions eq, eqOrNull, notEqual, in, inOrEmpty, notIn + gt, gtOrNull, ge, getOrNull, lt, ltOrNull, le, leOrNull, inRange, inRangeWith, between + synonyms
- PBaseString with additional expressions like, startsWith, endsWith, contains, match + case insensitive options

So we would look to create a new PScalar type as either:
- PScalar<T> extends PBaseCompareable<R, T> {
- PScalar<T> extends PBaseString<R, T> {
 
... we could either try and detect if the scalar wraps a String or just choose one knowing that some expressions would potentially not be valid for that type - e.g.  startWith() on a type that wraps a number would not be valid.

In the annotation processing we need to generate for the phoneNumber property:

PScalar<QMappingDBO, PhoneNumber> phoneNumber

So the annotation processor needs to either A) detect that PhoneNumber is valid scalarType and hence should generate the property or B) guess that it's a scalarType, generate the property and leave it up to the developer to NOT use it if it is actually invalid (but the property probably should have the transient modifier or @Transient if it wasn't a scalar type so guessing is maybe not as bad as it sounds).

So the B) "guess it's a scalarType and generate it" approach would be pretty simple.  Any type that isn't a know scalarType (String, Long etc) that also isn't transient/@Transient would get a PScalar property type generated into the query bean.  

For the A) approach of detecting it's a scalarType ... not sure how tricky that would be.

**Comment by tobias-** [comment]
There is no kotlin generator yet, I will do that when I know if this is something you want to add (and in this way) or if it's something you want to do in a different way.

NB. I cannot find any theoretical way of discovering if something has a ScalarType or not unless a new hard-coded condition that ScalarTypes MUST be in the same project as the `@Entities` (something that isn't true for some of our projects).

**Comment by rbygrave** [comment]
Well done, great work.

> There is no kotlin generator yet

Yes, we should add it in the same way.  I'm happy with what you have done.  I myself would have been happy enough not bothering to check for java.lang.Comparable and just made them all effectively PropertyTypeScalarComparable (in the sense that I'd rather just er on the side of freedom/power to developers rather than limit them).  

Great stuff.

**Comment by tobias-** [comment]
Thanks!

It's now your code, so change that as much as you like, but don't ask me how long it took to implement a simple instanceof in the APT-api. :)

The code for the kotlin-querybean-generator is done as well, but I failed to add a test case, so only managed to verify it via slightly modifying the example-kotlin project.

**Comment by rbygrave** [comment]
> how long it took to implement a simple instanceof in the APT-api. :)

Yeah, on one hand it is pretty cool that they provide this mechanism for javac and on the other hand the APT-api is just painful to work with.

**Comment by rbygrave** [comment]
Nice work, well done !!

**Comment by tobias-** [comment]
Thanks! You too. That was a quick merge.
